// Builds lib/match/opening_book_data.dart from a Stockfish opening book PGN.
//
// Usage:
//   curl -LO https://raw.githubusercontent.com/official-stockfish/books/master/8moves_v3.pgn.zip && unzip 8moves_v3.pgn.zip
//   dart run tool/build_opening_book.dart 8moves_v3.pgn [count] [seed]
//
// The book lines are replayed with chess_core so every stored move is known to be legal, then a fixed-seed random
// sample is written out as UCI move lines. Keeping the seed fixed means opening N is the same in every build.
import 'dart:io';
import 'dart:math';

import 'package:ace/chess_core/board.dart';
import 'package:ace/chess_core/game_result.dart';
import 'package:ace/chess_core/move.dart';
import 'package:ace/chess_core/san.dart';
import 'package:ace/match/pgn.dart';

void main(List<String> args) {
  if (args.isEmpty) {
    stderr.writeln("Usage: dart run tool/build_opening_book.dart <book.pgn> [count=500] [seed=2024]");
    exit(64);
  }
  int count = args.length > 1 ? int.parse(args[1]) : 500;
  int seed = args.length > 2 ? int.parse(args[2]) : 2024;

  List<PgnGame> games = PgnGame.parseAll(File(args[0]).readAsStringSync());
  Set<String> seen = {};
  List<String> lines = [];

  for (PgnGame game in games) {
    Board board = Board();
    List<String> uciMoves = [];
    for (PgnMove pgnMove in game.moves) {
      Move? move = San.toLegalMove(board, pgnMove.san);
      if (move == null) throw StateError("Illegal book move ${pgnMove.san} in line ${uciMoves.join(" ")}");
      uciMoves.add(move.toChessNotation());
      board.makeMove(move);
    }
    if (GameResult.check(board) != Result.playing) continue;
    if (seen.add(uciMoves.join(" "))) lines.add(uciMoves.join(" "));
  }

  lines.shuffle(Random(seed));
  List<String> sample = lines.take(count).toList();

  StringBuffer out = StringBuffer()
    ..writeln("// GENERATED by tool/build_opening_book.dart - do not edit by hand.")
    ..writeln("//")
    ..writeln("// $count opening lines sampled (seed $seed) from ${args[0].split("/").last} in the Stockfish opening books")
    ..writeln("// collection, https://github.com/official-stockfish/books, released under CC0 1.0 (public domain).")
    ..writeln("// Each line is 16 plies from the starting position, pre-selected by Stockfish to be roughly balanced.")
    ..writeln("// Each match plays every line twice with colours swapped.")
    ..writeln()
    ..writeln("const List<String> openingBook = [");
  for (String line in sample) {
    out.writeln('  "$line",');
  }
  out.writeln("];");

  File("lib/match/opening_book_data.dart").writeAsStringSync(out.toString());
  stdout.writeln("Parsed ${games.length} games, ${lines.length} unique lines, wrote ${sample.length}.");
}
